routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index');
Route::get('/about', 'PagesController@about');
Route::get('/services', 'PagesController@services');

Route::resource('posts','PostsController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Post extends Model
{
    // Table Name
    protected $table = 'posts';
    // PK
    public $primaryKey = 'id';

    //timestamps
    public $timestamps = true;

    protected $fillable = ['title', 'body'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PagesController extends Controller
{
    public function index(){
        $title = "Welcome to Index";
        // return view('pages/index', compact('title'));
        return view('pages/index')->with('title', $title);
    }  

    public function about(){
        $title = "Welcome to About";
        return view('pages/about', compact('title')) ;
    }  

    public function services(){
        $data = array(
            'title' => "Services",
            'services' => ['Design', 'Programming', 'Testing']
        );
        return view('pages/services') -> with($data);
    }  
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $posts= Post::orderBy('created_at','desc')->paginate(5);
        return view('posts/index')->with('posts', $posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required',
            'body' => 'required',
        ]);
        \App\Post::create($validatedData);

        return redirect('posts') ->with('success', 'Post Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post= Post::find($id);
        return view('posts/show') ->with ('post', $post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/inc/messages.blade.php
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div><br />
@endif


@if(session('success'))
    <div class="alert alert-success">
        {{session('success')}}
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger">
        {{session('error')}}
    </div>
@endif

resources/views/inc/navbar.blade.php
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-5">
        <div class ="container">
         <a class="navbar-brand " href="#">{{config('app.name', 'LSAPP')}}</a>
      
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/services">Services</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/posts">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
              </ul>

              <ul class="nav navbar-nav navbar-right">
                  <li class="nav-item">
                      <a class="nav-link" href="/posts/create">Create Posts</a>
                  </li>
              </ul>
            </div>
        </div>
    </nav>
      

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{{asset('css/app.css')}}">
        <title>{{config('app.name', 'LSAPP')}}</title>


    </head>
    <body>
      @include('inc/navbar')
      <div class="container">
        @include('inc/messages')
        @yield('content')
      </div>
    </body>
</html>

resources/views/pages/about.blade.php
@extends('layouts/app')

@section('content')
<h1>{{$title}}</h1>
<p>about page</p>

@endsection

resources/views/pages/index.blade.php
@extends('layouts.app')

@section('content')
<div class ="jumbotron text-center"> 
<h1>Welcome To  The Index Page</h1>
<p> This is the index page.</p>
<p><a class="btn btn-primary btn-lg" href="/login" role = button> Login <a> </p>

</div>
@endsection

resources/views/pages/services.blade.php
@extends('layouts/app')

@section('content')
    <h1>{{$title}}</h1>
    <ul class ="list-group">
    @if(count($services)>0)
        @foreach($services as $service)
        <li class="list-group-item">{{$service}}</li>
        @endforeach
    @endif
    </ul>


@endsection

resources/views/posts/create.blade.php
@extends('layouts/app')

@section('content')
 
 
    <div class="card uper">
        <div class="card-header">
          <h3>Create Post</h3>
        </div>
        <div class="card-body">
            <form method="post" action="{{ route('posts.store') }}">
                <div class="form-group">
                    @csrf
                    <label for="title">Title:</label>
                    <input type="text" class="form-control" name="title"/>
                </div>
                <div class="form-group">
                    <label for="body">Body:</label>
                    <textarea class="form-control" id="body" name='body' rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Post</button>
            </form>
        </div>
      </div>

@endsection

resources/views/posts/index.blade.php
@extends('layouts/app')

@section('content')
    <h3>Posts</h3>
    @if(count($posts) > 0)

        @foreach($posts as $post)
        <div class= "jumbotron">
        <h3> <a href="/posts/{{$post->id}}"> {{$post->title}} </a></h3>
            <small> Written on {{$post->created_at}} </small>
        </div>
        @endforeach
        {{$posts->links()}}
    @else
        <p>No posts found</p>
    @endif


@endsection

resources/views/posts/show.blade.php
@extends('layouts/app')

@section('content')
<a href="/posts" class="btn btn-secondary"> Go Back </a>
    <h1>{{$post->title}}</h1>
       
        <div class= "jumbotron">
        <div> {{$post->body}}  </div>
        <hr>
        <small> Written on {{$post->created_at}} </small>

        </div>
      


@endsection